# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: "ADA.gov"
# url: "https://example.gov" # the base hostname & protocol for your site, e.g. https://example.com.
# Required to support the jekyll-sitemap plugin below.
# Uncomment the url line when ready to push to production. If using different branches for multiple
# custom domains, edit this url parameter in the relevant branch to match the relevant custom domain.

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

permalink: pretty

include:
  - _pages

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - Dockerfile
  - docker-compose.yml
